Image Path:  tcia_idx                                                    557
dicom_path    /DATA/laura/datasets/chest_xray/train/NORMAL/I...
Name: 557, dtype: object
Traceback (most recent call last):
  File "/DATA/laura/code/PAM/main.py", line 48, in <module>
    main(args)
  File "/DATA/laura/code/PAM/main.py", line 14, in main
    net.train_disentanglement_method()
  File "/DATA/laura/code/PAM/disentanglement.py", line 576, in train_disentanglement_method
    self.train_Beta_VAE()
  File "/DATA/laura/code/PAM/disentanglement.py", line 219, in train_Beta_VAE
    for i, (x_1, x_2) in enumerate (self.train_dataloader):
  File "/DATA/laura/miniconda/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/DATA/laura/miniconda/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/DATA/laura/miniconda/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/DATA/laura/miniconda/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/DATA/laura/code/PAM/registration_dataset.py", line 31, in __getitem__
    print("fixed: ", fixed.shape)
  File "/DATA/laura/miniconda/envs/pytorch/lib/python3.10/site-packages/PIL/Image.py", line 517, in __getattr__
    raise AttributeError(name)
AttributeError: shape